export const SUBJECTS_LIST = [
  { id: 0, name: "Arabic" },
  { id: 1, name: "English" },
  { id: 2, name: "Deutsch" },
  { id: 3, name: "Italiano" },
  { id: 4, name: "Français" },
  { id: 5, name: "Español" },
  { id: 6, name: "Math" },
  { id: 7, name: "Physics" },
  { id: 8, name: "Chemistry" },
  { id: 9, name: "Biology" },
  { id: 10, name: "Geology" },
  { id: 11, name: "History" },
  { id: 12, name: "Geography" },
  { id: 13, name: "Philosophy" },
  { id: 14, name: "Psychology" },
  { id: 15, name: "Science" },
  { id: 16, name: "SocialStudies" },
];