const API_BASE_URL = "https://localhost:7251";
const SEARCH_TEACHER_API = `${API_BASE_URL}/Search`;
const FILTER_TEACHER_API = `${API_BASE_URL}/Filter`;
const ALL_TEACHER_API = `${API_BASE_URL}/GetAllTeachers`;
export {SEARCH_TEACHER_API, FILTER_TEACHER_API, ALL_TEACHER_API};